context:
  aboutText: Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at <a href="https://mozilla.org">mozilla.org</a> 
variants:
  - name: Short about text
    context:
      aboutText: Mozilla is a global non-profit.
  - name: Blue background
    context:
      modifier: footer--blue