context:
  aboutText: Mozilla is a global non-profit dedicated to putting you in control of your online experience and shaping the future of the web for the public good. Visit us at <a href="https://mozilla.org">mozilla.org</a> 
  links:
   - text: Contribute
     icon: contribute.svg
     href: https://github.com/mozilla/coss
   - text: Legal
     icon: legal.svg 
     href: https://www.mozilla.org/en-US/about/legal/
   - text: Privacy
     icon: privacy.svg
     href: https://www.mozilla.org/en-US/privacy/
variants:
  - name: Short about text
    context:
      aboutText: Mozilla is a global non-profit.
  - name: Blue background
    context:
      modifier: footer--blue
  - name: No links
    context:
      links: ''